
(7, 'Tom Brown', 31, 'Cashier', 'tom.brown@yahoo.com',8),
(8, 'Emily Clark', 33, 'Cashier', 'emily.clark@yahoo.com',8),
(9, 'Daniel King', 30, 'Cashier', 'daniel.king@yahoo.com',8),
(10, 'Laura Scott', 27, 'Cashier', 'laura.scott@yahoo.com',8),
(11, 'Jack Hill', 34, 'Cashier', 'jack.hill@yahoo.com',8),
(12, 'Olivia Adams', 29, 'Cashier', 'olivia.adams@yahoo.com',8),
(13, 'Liam Turner', 28, 'Cashier', 'liam.turner@yahoo.com',8),
(14, 'Sophia Evans', 31, 'Cashier', 'sophia.evans@yahoo.com',8),
(15, 'Mason Hall', 32, 'Cashier', 'mason.hall@yahoo.com',8),
(16, 'Ella Ward', 27, 'Cashier', 'ella.ward@yahoo.com',8),
(17, 'Jacob Carter', 30, 'Cashier', 'jacob.carter@yahoo.com',8),
(18, 'Ava Mitchell', 35, 'Cashier', 'ava.mitchell@yahoo.com',8),
(19, 'Michael Brooks', 29, 'Cashier', 'michael.brooks@yahoo.com',8),
(20, 'Grace Lewis', 28, 'Cashier', 'grace.lewis@yahoo.com',8),
(21, 'Alice Johnson', 30, 'Supervisor', 'alice.johnson@gmail.com',8),
(22, 'Bob Smith', 28, 'Supervisor', 'bob.smith@gmail.com',8),