# Generated by Django 5.0.10 on 2025-03-01 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HRManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ManagerID', models.CharField(default='0000', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Manager ID must be exactly 4 digits')])),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(default='HRManager', max_length=150)),
                ('email', models.EmailField(default='hrmanager@gmail.com', max_length=254, unique=True)),
            ],
        ),
    ]
