import os
import django
import sys

sys.path.append('C:\\django\\SAS_final\\SAS')
# Set the DJANGO_SETTINGS_MODULE environment variable to your settings module
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')

# Initialize Django
django.setup()

from configure.models import Employee
# Insert Employee Data
employee_data = [(1, 'John Doe', 0, 'Manager', 'john.doe@example.com', 9),
    (2, 'Jane Smith', 0, 'Customer Help', 'jane.smith@example.com', 8),
    (3, 'Mark Lee', 0, 'Supervisor', 'mark.lee@example.com', 8),
    (4, 'Anna White', 0, 'Cleaning Staff', 'anna.white@example.com', 4),
    (5, 'Chris Green', 0, 'Inventory Manager', 'chris.green@example.com', 6),
    (6, 'Sarah Black', 0, 'Cashier', 'sarah.black@example.com', 8),
    (7, 'Tom Brown', 0, 'Cleaning Staff', 'tom.brown@example.com', 8),
    (8, 'Emily Clark', 0, 'Customer Help', 'emily.clark@example.com', 8),
    (9, 'Daniel King', 0, 'Supervisor', 'daniel.king@example.com', 8),
    (10, 'Laura Scott', 0, 'Cashier', 'laura.scott@example.com', 8),
    (11, 'Jack Hill', 0, 'Supervisor', 'jack.hill@example.com', 8),
    (12, 'Olivia Adams', 0, 'Cleaning Staff', 'olivia.adams@example.com', 4),
    (13, 'Liam Turner', 0, 'Cleaning Staff', 'liam.turner@example.com', 4),
    (14, 'Sophia Evans', 0, 'Inventory Manager', 'sophia.evans@example.com', 6),
    (15, 'Mason Hall', 0, 'Inventory Manager', 'mason.hall@example.com', 6),
    (16, 'Ella Ward', 0, 'Supervisor', 'ella.ward@example.com', 8),
    (17, 'Jacob Carter', 0, 'Manager', 'jacob.carter@example.com', 9),
    (18, 'Ava Mitchell', 0, 'Cleaning Staff', 'ava.mitchell@example.com', 4),
    (19, 'Michael Brooks', 0, 'Customer Help', 'michael.brooks@example.com', 8),
    (20, 'Grace Lewis', 0, 'Cleaning Staff', 'grace.lewis@example.com', 4),
    (21, 'Alice Johnson', 0, 'Cashier', 'alice.johnson@example.com', 8),
    (22, 'Bob Smith', 0, 'Supervisor', 'bob.smith@example.com', 8),
    (23, 'Charlie Davis', 0, 'Inventory Manager', 'charlie.davis@example.com', 6),
    (24, 'Diana Clark', 0, 'Customer Help', 'diana.clark@example.com', 8),
    (25, 'Ethan Brown', 0, 'Supervisor', 'ethan.brown@example.com', 8),
    (26, 'Fiona Adams', 0, 'Cashier', 'fiona.adams@example.com', 8),
    (27, 'George Miller', 0, 'Inventory Manager', 'george.miller@example.com', 6),
    (28, 'Hannah White', 0, 'Customer Help', 'hannah.white@example.com', 8),
    (29, 'Isaac Wilson', 0, 'Manager', 'isaac.wilson@example.com', 9),
    (30, 'Julia Thomas', 0, 'Cleaning Staff', 'julia.thomas@example.com', 4),
    (31, 'Kevin Moore', 0, 'Cashier', 'kevin.moore@example.com', 8),
    (32, 'Liam Taylor', 0, 'Supervisor', 'liam.taylor@example.com', 8),
    (33, 'Mia Scott', 0, 'Customer Help', 'mia.scott@example.com', 8),
    (34, 'Nathan Harris', 0, 'Inventory Manager', 'nathan.harris@example.com', 6),
    (35, 'Olivia Martinez', 0, 'Supervisor', 'olivia.martinez@example.com', 8),
    (36, 'Peter Robinson', 0, 'Manager', 'peter.robinson@example.com', 9),
    (37, 'Quinn Lewis', 0, 'Cashier', 'quinn.lewis@example.com', 8),
    (38, 'Rachel Walker', 0, 'Cleaning Staff', 'rachel.walker@example.com', 4),
    (39, 'Samuel Allen', 0, 'Customer Help', 'samuel.allen@example.com', 8),
    (40, 'Tina Young', 0, 'Supervisor', 'tina.young@example.com', 8),
    (41, 'John Smith', 0, 'Inventory Manager', 'john.smith@example.com', 6),
    (42, 'Alice Brown', 0, 'Cashier', 'alice.brown@example.com', 8),
    (43, 'Bob Johnson', 0, 'Customer Help', 'bob.johnson@example.com', 8),
    (44, 'Carol White', 0, 'Cashier', 'carol.white@example.com', 8),
    (45, 'David Green', 0, 'Cleaning Staff', 'david.green@example.com', 4),
    (46, 'Eva Adams', 0, 'Manager', 'eva.adams@example.com', 9),
    (47, 'Frank Lee', 0, 'Inventory Manager', 'frank.lee@example.com', 6),
    (48, 'Grace Miller', 0, 'Supervisor', 'grace.miller@example.com', 8),
    (49, 'Harry Clark', 0, 'Customer Help', 'harry.clark@example.com', 8),
    (50, 'Ivy Scott', 0, 'Cleaning Staff', 'ivy.scott@example.com', 4),
    (51, 'Jack Walker', 0, 'Cashier', 'jack.walker@example.com', 8),
    (52, 'Kathy Hall', 0, 'Manager', 'kathy.hall@example.com', 9),
    (53, 'Liam Allen', 0, 'Cashier', 'liam.allen@example.com', 8),
    (54, 'Mona Perez', 0, 'Supervisor', 'mona.perez@example.com', 8),
    (55, 'Nathan Young', 0, 'Inventory Manager', 'nathan.young@example.com', 6),
    (56, 'Olivia Foster', 0, 'Customer Help', 'olivia.foster@example.com', 8),
    (57, 'Paul Carter', 0, 'Inventory Manager', 'paul.carter@example.com', 6),
    (58, 'Quincy Adams', 0, 'Cashier', 'quincy.adams@example.com', 8),
    (59, 'Ryan Brooks', 0, 'Cleaning Staff', 'ryan.brooks@example.com', 4),
    (60, 'Sophia Turner', 0, 'Supervisor', 'sophia.turner@example.com', 8),
    (61, 'Travis King', 0, 'Manager', 'travis.king@example.com', 9),
    (62, 'Uma Watson', 0, 'Customer Help', 'uma.watson@example.com', 8),
    (63, 'Vincent Harris', 0, 'Inventory Manager', 'vincent.harris@example.com', 6),
    (64, 'Wendy Lopez', 0, 'Cashier', 'wendy.lopez@example.com', 8),
    (65, 'Xavier Evans', 0, 'Cleaning Staff', 'xavier.evans@example.com', 4),
    (66, 'Yvonne Green', 0, 'Supervisor', 'yvonne.green@example.com', 8),
    (67, 'Zachary Nelson', 0, 'Manager', 'zachary.nelson@example.com', 9),
    (68, 'Adam Wright', 0, 'Customer Help', 'adam.wright@example.com', 8),
    (69, 'Bethany Hall', 0, 'Inventory Manager', 'bethany.hall@example.com', 6),
    (70, 'Charles Mitchell', 0, 'Cashier', 'charles.mitchell@example.com', 8),
    (71, 'Debra Stewart', 0, 'Cleaning Staff', 'debra.stewart@example.com', 4),
    (72, 'Ethan Parker', 0, 'Supervisor', 'ethan.parker@example.com', 8),
    (73, 'Felicity Adams', 0, 'Manager', 'felicity.adams@example.com', 9),
    (74, 'George Bailey', 0, 'Customer Help', 'george.bailey@example.com', 8),
    (75, 'Holly Roberts', 0, 'Inventory Manager', 'holly.roberts@example.com', 6),
    (76, 'Ian Walker', 0, 'Cashier', 'ian.walker@example.com', 8),
    (77, 'Jasmine Cooper', 0, 'Cleaning Staff', 'jasmine.cooper@example.com', 4),
    (78, 'Kyle Thomas', 0, 'Supervisor', 'kyle.thomas@example.com', 8),
    (79, 'Laura Phillips', 0, 'Manager', 'laura.phillips@example.com', 9),
    (80, 'Mike Russell', 0, 'Customer Help', 'mike.russell@example.com', 8),
    (81, 'Nancy Scott', 0, 'Inventory Manager', 'nancy.scott@example.com', 6),
    (82, 'Oscar Reed', 0, 'Cashier', 'oscar.reed@example.com', 8),
    (83, 'Paula Jenkins', 0, 'Cleaning Staff', 'paula.jenkins@example.com', 4),
    (84, 'Quinn Simmons', 0, 'Supervisor', 'quinn.simmons@example.com', 8),
    (85, 'Rachel Murphy', 0, 'Manager', 'rachel.murphy@example.com', 9),
    (86, 'Steve Bennett', 0, 'Customer Help', 'steve.bennett@example.com', 8),
    (87, 'Tracy Wood', 0, 'Inventory Manager', 'tracy.wood@example.com', 6),
    (88, 'Ulysses Foster', 0, 'Cashier', 'ulysses.foster@example.com', 8),
    (89, 'Victoria Nelson', 0, 'Cleaning Staff', 'victoria.nelson@example.com', 4),
    (90, 'Walter Carter', 0, 'Supervisor', 'walter.carter@example.com', 8),
    (91, 'Xander Hayes', 0, 'Manager', 'xander.hayes@example.com', 9),
    (92, 'Yasmine Torres', 0, 'Customer Help', 'yasmine.torres@example.com', 8),
    (93, 'Zane Patterson', 0, 'Inventory Manager', 'zane.patterson@example.com', 6),
    (94, 'Abigail Morgan', 0, 'Cashier', 'abigail.morgan@example.com', 8),
    (95, 'Benjamin Hughes', 0, 'Cleaning Staff', 'benjamin.hughes@example.com', 4),
    (96, 'Charlotte Wright', 0, 'Supervisor', 'charlotte.wright@example.com', 8),
    (97, 'Daniel Brooks', 0, 'Manager', 'daniel.brooks@example.com', 9),
    (98, 'Eleanor Fisher', 0, 'Customer Help', 'eleanor.fisher@example.com', 8),
    (99, 'Felix Richardson', 0, 'Inventory Manager', 'felix.richardson@example.com', 6),
    (100, 'Giselle Howard', 0, 'Cashier', 'giselle.howard@example.com', 8) ,
 (101, 'Henry Coleman', 0, 'Cleaning Staff', 'henry.coleman@example.com', 4),
    (102, 'Isla Ward', 0, 'Supervisor', 'isla.ward@example.com', 8),
    (103, 'Jack Foster', 0, 'Manager', 'jack.foster@example.com', 9),
    (104, 'Karen Hughes', 0, 'Customer Help', 'karen.hughes@example.com', 8),
    (105, 'Leo Morris', 0, 'Inventory Manager', 'leo.morris@example.com', 6),
    (106, 'Mia Bennett', 0, 'Cashier', 'mia.bennett@example.com', 8),
    (107, 'Noah Carter', 0, 'Cleaning Staff', 'noah.carter@example.com', 4),
    (108, 'Olive Nelson', 0, 'Supervisor', 'olive.nelson@example.com', 8),
    (109, 'Patrick Evans', 0, 'Manager', 'patrick.evans@example.com', 9),
    (110, 'Quinn Brooks', 0, 'Customer Help', 'quinn.brooks@example.com', 8),
    (111, 'Rebecca Scott', 0, 'Inventory Manager', 'rebecca.scott@example.com', 6),
    (112, 'Samuel Harris', 0, 'Cashier', 'samuel.harris@example.com', 8),
    (113, 'Tina Mitchell', 0, 'Cleaning Staff', 'tina.mitchell@example.com', 4),
    (114, 'Umar White', 0, 'Supervisor', 'umar.white@example.com', 8),
    (115, 'Violet Reed', 0, 'Manager', 'violet.reed@example.com', 9),
    (116, 'Walter Adams', 0, 'Customer Help', 'walter.adams@example.com', 8),
    (117, 'Xena Lewis', 0, 'Inventory Manager', 'xena.lewis@example.com', 6),
    (118, 'Yusuf Green', 0, 'Cashier', 'yusuf.green@example.com', 8),
    (119, 'Zara Hill', 0, 'Cleaning Staff', 'zara.hill@example.com', 4),
    (120, 'Adam Parker', 0, 'Supervisor', 'adam.parker@example.com', 8)
]

for e in employee_data:
    Employee.objects.create(
        e_id=e[0], e_name=e[1], no_of_hours_worked=e[2], 
        designation=e[3], e_gmail=e[4], e_priority=e[5]
    )

